config/routes.rb
TdewEstacionamiento::Application.routes.draw do
  
  get "estacionamientos/contador"
  
  get "estacionamientos/rlocal"
  
  get "estacionamientos/home_operador"

  get "alumnos/configuracion"
  

  
  get "alumnos/login"

  root :to => 'navigation#home'

  resources :alumnos

  resources :estacionamientos

end

app/models/alumno.rb
class Alumno < ActiveRecord::Base
end

app/models/estacionamiento.rb
class Estacionamiento < ActiveRecord::Base
end

app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  # GET /alumnos
  # GET /alumnos.json
  def index
    @alumnos = Alumno.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alumnos }
    end
  end

  # GET /alumnos/1
  # GET /alumnos/1.json
  def show
    @alumno = Alumno.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @alumno }
    end
  end

  # GET /alumnos/new
  # GET /alumnos/new.json
  def new
    @alumno = Alumno.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @alumno }
    end
  end

  # GET /alumnos/1/edit
  def edit
    @alumno = Alumno.find(params[:id])
  end

  # POST /alumnos
  # POST /alumnos.json
  def create
    @alumno = Alumno.new(params[:alumno])

    respond_to do |format|
      if @alumno.save
        format.html { redirect_to @alumno, notice: 'Alumno was successfully created.' }
        format.json { render json: @alumno, status: :created, location: @alumno }
      else
        format.html { render action: "new" }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /alumnos/1
  # PUT /alumnos/1.json
  def update
    @alumno = Alumno.find(params[:id])

    respond_to do |format|
      if @alumno.update_attributes(params[:alumno])
        format.html { redirect_to @alumno, notice: 'Alumno was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1
  # DELETE /alumnos/1.json
  def destroy
    @alumno = Alumno.find(params[:id])
    @alumno.destroy

    respond_to do |format|
      format.html { redirect_to alumnos_url }
      format.json { head :ok }
    end
  end

  def login
  #link_to "login", "navigation/login"
  end

  def configuracion

  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/estacionamientos_controller.rb
class EstacionamientosController < ApplicationController
  # GET /estacionamientos
  # GET /estacionamientos.json
  def index
    @estacionamientos = Estacionamiento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @estacionamientos }
    end
  end

  # GET /estacionamientos/1
  # GET /estacionamientos/1.json
  def show
    @estacionamiento = Estacionamiento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @estacionamiento }
    end
  end

  # GET /estacionamientos/new
  # GET /estacionamientos/new.json
  def new
    @estacionamiento = Estacionamiento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @estacionamiento }
    end
  end

  # GET /estacionamientos/1/edit
  def edit
    @estacionamiento = Estacionamiento.find(params[:id])
  end

  # POST /estacionamientos
  # POST /estacionamientos.json
  def create
    @estacionamiento = Estacionamiento.new(params[:estacionamiento])

    respond_to do |format|
      if @estacionamiento.save
        format.html { redirect_to @estacionamiento, notice: 'Estacionamiento was successfully created.' }
        format.json { render json: @estacionamiento, status: :created, location: @estacionamiento }
      else
        format.html { render action: "new" }
        format.json { render json: @estacionamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /estacionamientos/1
  # PUT /estacionamientos/1.json
  def update
    @estacionamiento = Estacionamiento.find(params[:id])

    respond_to do |format|
      if @estacionamiento.update_attributes(params[:estacionamiento])
        format.html { redirect_to @estacionamiento, notice: 'Estacionamiento was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @estacionamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estacionamientos/1
  # DELETE /estacionamientos/1.json
  def destroy
    @estacionamiento = Estacionamiento.find(params[:id])
    @estacionamiento.destroy

    respond_to do |format|
      format.html { redirect_to estacionamientos_url }
      format.json { head :ok }
    end
  end

  def rlocal
  #link_to "login", "navigation/login"
  end

  def contador
  @estacionamientos = Estacionamiento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @estacionamientos }
    end
  end
end

app/controllers/navigation_controller.rb
class NavigationController < ApplicationController
  def home
	@estacionamientos = Estacionamiento.all

    	respond_to do |format|
      	format.html # index.html.erb
      	format.json { render json: @estacionamientos }
    	end
  	end


end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estacionamientos_helper.rb
module EstacionamientosHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper
end

app/views/alumnos/_form.html.erb
<%= form_for(@alumno) do |f| %>
  <% if @alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alumno.errors.count, "error") %> prohibited this alumno from being saved:</h2>

      <ul>
      <% @alumno.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :dias %><br />
    <%= f.text_field :dias %>
  </div>
  <div class="field">
    <%= f.label :hora %><br />
    <%= f.text_field :hora %>
  </div>
  <div class="field">
    <%= f.label :notificacion %><br />
    <%= f.text_field :notificacion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alumnos/configuracion.html.erb
<h1>Configuración</h1>

<p>Usted debe configurar su cuenta</p>
<p>
Alumno: XXX
</p>

<p>
Seleccionar una opción
<div class="well">
            
            <div class="input">
              <ul class="inputs-list">
                <li>
                  <label>
                    <input type="radio" checked name="optionsRadios" value="option1" />
                    <span>Si, deseo configurar mi cuenta para recibir notificaciones de disponibildiad de los estacionamientos</span>
                  </label>
                </li>
                <li>
                  <label>
                    <input type="radio" name="optionsRadios" value="option2" />
                    <span>No, no estoy interesado</span>
                  </label>
                </li>
              </ul>
            </div>
          </div>
</p>
<p>
<hr>
</p>
<p>
<section id="grid-system">

<div class="row show-grid" title="Half and half">
    <div class="span8">

 <legend><B>Seleccione los días e ingrese la hora</B></legend>
          <div class="clearfix">
            
            <div class="input">
              <ul class="inputs-list">
                <li>
                  <label>
                    <input type="checkbox" name="optionsCheckboxes" value="option1" />
                    <span>Lunes</span>
                    <span> &Hora: <input class="mini" id="mini" name="mini" size="30" type="text" /></span>
                  </label>
                </li>
                <li>
                  <label>
                    <input type="checkbox" name="optionsCheckboxes" value="option2" />
                    <span>Martes</span>
                    <span> Hora: <input class="mini" id="mini" name="mini" size="30" type="text" /></span>
                  </label>
                </li>
                <li>
                  <label>
                    <input type="checkbox" name="optionsCheckboxes" value="option2" />
                    <span>Miercoles</span>
                    <span> Hora: <input class="mini" id="mini" name="mini" size="30" type="text" /></span>
                  </label>
                </li>
                <li>
                  <label>
                    <input type="checkbox" name="optionsCheckboxes" value="option2" />
                    <span>Jueves</span>
                    <span> Hora: <input class="mini" id="mini" name="mini" size="30" type="text" /></span>
                  </label>
                </li>
                <li>
                  <label>
                    <input type="checkbox" name="optionsCheckboxes" value="option2" />
                    <span>Viernes</span>
                    <span> Hora: <input class="mini" id="mini" name="mini" size="30" type="text" /></span>
                  </label>
                </li>
                <li>
                  <label>
                    <input type="checkbox" name="optionsCheckboxes" value="option2" />
                    <span>Sabado</span>
                    <span> Hora: <input class="mini" id="mini" name="mini" size="30" type="text" /></span>
                  </label>
                </li>
                <li>
                  <label class="disabled">
                    <input type="checkbox" name="optionsCheckboxes" value="option2" disabled />
                    <span>Domingo</span>
                    <span> Hora: <input class="mini" id="mini" name="mini" size="30" type="text" disabled /></span>
                  </label>
                </li>

              </ul>
              <span class="help-block">
                <strong>Nota:</strong> Seleccionar Dia y la hora que desea ser notificado.
              </span>
            </div>
          </div><!-- /clearfix -->
    </div>
    <div class="span8">
    <br>




<div class="actions">
            <input type="submit" class="btn primary" value="Activar Notificacioesn">&nbsp;<button type="reset" class="btn">Cancelar</button>
          </div>


    </div>
</div><!-- /row -->
</section>
   

</p>
<hr>
<%= link_to "Atras","login" %>

app/views/alumnos/edit.html.erb
<h1>Editing alumno</h1>

<%= render 'form' %>

<%= link_to 'Show', @alumno %> |
<%= link_to 'Back', alumnos_path %>

app/views/alumnos/index.html.erb
<h1>Listing alumnos</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th>Nombre</th>
    <th>Dias</th>
    <th>Hora</th>
    <th>Notificacion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @alumnos.each do |alumno| %>
  <tr>
    <td><%= alumno.codigo %></td>
    <td><%= alumno.nombre %></td>
    <td><%= alumno.dias %></td>
    <td><%= alumno.hora %></td>
    <td><%= alumno.notificacion %></td>
    <td><%= link_to 'Show', alumno %></td>
    <td><%= link_to 'Edit', edit_alumno_path(alumno) %></td>
    <td><%= link_to 'Destroy', alumno, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Alumno', new_alumno_path %>

app/views/alumnos/login.html.erb
<h1>Login</h1>
<p>Ingresa tu Código de Alumno UPC</p>

<p>
	<div class="well">
		 <p>
		 	<div class="clearfix" style="position:relative; left:-100;">
		 	<label for="xlInput">Email Alumno: </label>
	            <div class="input">
	              <input class="xlarge" id="xlInput" name="xlInput" size="30" type="text" />
	            </div>
            </div>
         </p>
        <a href="configuracion" class="btn large primary">Configurar</a>
        <a href="#" class="btn large">Cancelar</a>
  	</div>

</p>

app/views/alumnos/new.html.erb
<h1>New alumno</h1>

<%= render 'form' %>

<%= link_to 'Back', alumnos_path %>

app/views/alumnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @alumno.codigo %>
</p>

<p>
  <b>Nombre:</b>
  <%= @alumno.nombre %>
</p>

<p>
  <b>Dias:</b>
  <%= @alumno.dias %>
</p>

<p>
  <b>Hora:</b>
  <%= @alumno.hora %>
</p>

<p>
  <b>Notificacion:</b>
  <%= @alumno.notificacion %>
</p>


<%= link_to 'Edit', edit_alumno_path(@alumno) %> |
<%= link_to 'Back', alumnos_path %>

app/views/estacionamientos/_form.html.erb
<%= form_for(@estacionamiento) do |f| %>
  <% if @estacionamiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estacionamiento.errors.count, "error") %> prohibited this estacionamiento from being saved:</h2>

      <ul>
      <% @estacionamiento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :local %><br />
    <%= f.text_field :local %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br />
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :capacidad %><br />
    <%= f.number_field :capacidad %>
  </div>
  <div class="field">
    <%= f.label :disponible %><br />
    <%= f.number_field :disponible %>
  </div>
  <div class="field">
    <%= f.label :mensaje %><br />
    <%= f.text_field :mensaje %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estacionamientos/contador.html.erb
<h1>Ingresos y Salidas de Autos</h1>
<p>
<div class="input">
              Seleccionar Local: <select class="large" name="mediumSelect" id="mediumSelect">
              <% @estacionamientos.each do |estacionamiento|%>
                <option><%= estacionamiento.local %></option>
              <% end %>
              </select>
    </div>
</p>
<HR>
<P>
<a href="configuracion" class="btn large primary">Ingreso un Auto</a>
        <a href="#" class="btn large danger">Salio un Auto</a>
</P>
<HR>
<%= link_to "Volver a menu","home_operador" %>

app/views/estacionamientos/edit.html.erb
<h1>Editing estacionamiento</h1>

<%= render 'form' %>

<%= link_to 'Show', @estacionamiento %> |
<%= link_to 'Back', estacionamientos_path %>

app/views/estacionamientos/home_operador.html.erb
<h1>Operador</h1>
<p><div class="well"><%= link_to "Registrar Estacionamiento","../estacionamientos" %></div></p>
<p><div class="well"><%= link_to "Contador de Autos","contador" %></div></p>

app/views/estacionamientos/index.html.erb
<h1>Lista de Estacionamientos</h1>

<table>
  <tr>
    <th>Local</th>
    <th>Direccion</th>
    <th>Capacidad</th>
    <th>Disponible</th>
    <th>Mensaje</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @estacionamientos.each do |estacionamiento| %>
  <tr>
    <td><%= estacionamiento.local %></td>
    <td><%= estacionamiento.direccion %></td>
    <td><%= estacionamiento.capacidad %></td>
    <td><%= estacionamiento.disponible %></td>
    <td><%= estacionamiento.mensaje %></td>
    <td><%= link_to 'Ver', estacionamiento %></td>
    <td><%= link_to 'Editar', edit_estacionamiento_path(estacionamiento) %></td>
    <td><%= link_to 'Borrar', estacionamiento, confirm: 'Esta seguro?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo Estacionamiento', new_estacionamiento_path %> | 
<%= link_to 'Volver', '../estacionamientos/home_operador' %>

app/views/estacionamientos/new.html.erb
<h1>New estacionamiento</h1>

<%= render 'form' %>

<%= link_to 'Back', estacionamientos_path %>

app/views/estacionamientos/rlocal.html.erb
<h1>Registro del Estacionamiento</h1>
<p>Debe registrar un Nuevo estacionamiento</p>
<p>

</p>
<hr>
<%= link_to "Volver a menu","home_operador" %>

app/views/estacionamientos/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Detalle del Registro</h1>
<p>
  <b>Local:</b>
  <%= @estacionamiento.local %>
</p>

<p>
  <b>Direccion:</b>
  <%= @estacionamiento.direccion %>
</p>

<p>
  <b>Capacidad:</b>
  <%= @estacionamiento.capacidad %>
</p>

<p>
  <b>Disponible:</b>
  <%= @estacionamiento.disponible %>
</p>

<p>
  <b>Mensaje:</b>
  <%= @estacionamiento.mensaje %>
</p>


<%= link_to 'Editar', edit_estacionamiento_path(@estacionamiento) %> |
<%= link_to 'Volver', estacionamientos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TdewEstacionamiento</title>
  <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<style type="text/css">
      /* Override some defaults */
      html, body {
        background-color: #eee;
      }
      body {
        padding-top: 40px; /* 40px to make the container go all the way to the bottom of the topbar */
      }
      .container > footer p {
        text-align: center; /* center align it with the container */
      }
      .container {
        width: 820px; /* downsize our container to make the content feel a bit tighter and more cohesive. NOTE: this removes two full columns from the grid, meaning you only go to 14 columns and not 16. */
      }
 
      /* The white background content wrapper */
      .content {
        background-color: #fff;
        padding: 20px;
        margin: 0 -20px; /* negative indent the amount of the padding to maintain the grid system */
        -webkit-border-radius: 0 0 6px 6px;
           -moz-border-radius: 0 0 6px 6px;
                border-radius: 0 0 6px 6px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
                box-shadow: 0 1px 2px rgba(0,0,0,.15);
      }
 
      /* Page header tweaks */
      .page-header {
        background-color: #f5f5f5;
        padding: 20px 20px 10px;
        margin: -20px -20px 20px;
      }
 
      /* Styles you shouldn't keep as they are for displaying this base example only */
      .content .span10,
      .content .span4 {
        min-height: 500px;
      }
      /* Give a quick and non-cross-browser friendly divider */
      .content .span4 {
        margin-left: 0;
        padding-left: 19px;
        border-left: 1px solid #eee;
      }
 
      .topbar .btn {
        border: 0;
      }
 
    </style>
 
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
  </head>
 
  <body>
 
    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="#">Estacionamiento</a>
          <ul class="nav">
            <li class="active"><a href="../">Home</a></li>
            <li><a href="../alumnos/login#about">Alumno</a></li>
            <li><a href="../estacionamientos/home_operador">Operador</a></li>
          </ul>
          <form action="" class="pull-right">
            <input class="input-small" type="text" placeholder="Username">
            <input class="input-small" type="password" placeholder="Password">
            <button class="btn" type="submit">Sign in</button>
          </form>
        </div>
      </div>
    </div>
 
    <div class="container">
 
      <div class="content">
        <%= yield %>
      </div>
 
      <footer>
        <p>&copy; UPC-TryDEW 2011</p>
      </footer>
 
    </div> <!-- /container -->
 
  </body>
</html>



</body>
</html>

app/views/navigation/activacion.html.erb
<h1>Navigation#activacion</h1>
<p>Find me in app/views/navigation/activacion.html.erb</p>

app/views/navigation/configuracion.html.erb
<h1>Navigation#configuracion</h1>
<p>Find me in app/views/navigation/configuracion.html.erb</p>

app/views/navigation/contador.html.erb
<h1>Navigation#contador</h1>
<p>Find me in app/views/navigation/contador.html.erb</p>

app/views/navigation/home.html.erb
<h1>¿Quieres saber si hay Estacionamiento disponible en la UPC?</h1>
<p>Bienevenidos a Estacionamiento UPC, donde podrás saber en el momento que decidas la disponibildad de espacios en los estacionamientos de la UPC.
</p>

<p>
<table>
  

<% @estacionamientos.each do |estacionamiento| %>
  <tr>
    <td><%= estacionamiento.local %></td>
    <td><%= estacionamiento.direccion %></td>
    <td><%= estacionamiento.capacidad %></td>
    <td style="color:#006699; font-weight:bolder;"><%= estacionamiento.disponible %></td>
  </tr>
<% end %>
</table>
</p>
<hr>
<p>
<div class="well">
<%= link_to "Desea Configurar sus notificaciones", "alumnos/login"%>
</div>
</p>

app/views/navigation/login.html.erb
<h1>Login</h1>
<p>Ingresa tu Código de Alumno UPC</p>

<p>
	<div class="well">
		 <p>
		 	<div class="clearfix" style="position:relative; left:-100;">
		 	<label for="xlInput">Codigo Alumno: </label>
	            <div class="input">
	              <input class="xlarge" id="xlInput" name="xlInput" size="30" type="text" />
	            </div>
            </div>
         </p>
        <a href="" class="btn large primary">Configurar</a>
        <a href="#" class="btn large">Cancelar</a>
  	</div>

</p>

app/views/navigation/rlocal.html.erb
<h1>Navigation#rlocal</h1>
<p>Find me in app/views/navigation/rlocal.html.erb</p>